### ISSUE TITLE
error: unauthorized

### ISSUE THREAD

**Issue by NuxRo** [devel/PowerDNS-API#31]
Hi,

I installed your software and no matter if I run it as production or development I'm still getting this error after I auth:

{
   "error" : "unauthorized"
}

My request is something like:
http://192.168.0.66:8080/api/domain/example.com

Production log sample: http://fpaste.org/yovg/
Development log: http://fpaste.org/Qs3e/

Please advise.

**Comment by abh** [comment]
Did you setup an account with the

`./script/powerdns_api account username password`

command?

I will add some more documentation on the wiki.

**Comment by abh** [comment]
Does this help?

https://github.com/devel/PowerDNS-API/wiki/Authentication

**Comment by NuxRo** [comment]
I have created a user as per your instructions. No matter if the credentials are correct or not all I get is this:
http://fpaste.org/OsNU/

This is how my powerdns-api.conf looks like:
http://fpaste.org/JuW9/

Can you confirm the "secret" can be any random string?

**Comment by abh** [comment]
The secret can be any random string. It's sha256'ed with a salt before saving in the database.

It looks like you are getting the homepage, be sure to call the path `/api/domain/` (for example) to get the list of domains.  https://github.com/devel/PowerDNS-API/wiki/REST-API

**Comment by abh** [comment]
Oh, I misunderstood.  Yes, that secret can be any random string. It just has to be the same if you have multiple API servers behind a load balancer for example.

**Comment by NuxRo** [comment]
"/api/domain/" returns:
{
   "domains" : []
}

Trying http://localhost:3000/api/domain/domain.tld returns:
{
   "error" : "unauthorized"
}

The domain exists, of course ...

**Comment by abh** [comment]
Make sure the 'account' column for 'domain.tld' in the domains table have the account name you are using.

**Comment by NuxRo** [comment]
Riiight! Now we're getting somewhere; there was no account specified (NULL). I added it with:
update domains set account="apiuser";

I'm working with an existing database, but I have imported your schema.

Now when I'm trying to access hypnotoad I get:
[Mon Sep 17 19:44:15 2012] [error] DBIx::Class::ResultSet::all(): DBI Exception: DBD::mysql::st execute failed: Unknown column 'me.ordername' in 'field list' at /home/powerdnsapi/PowerDNS-API/script/../lib/PowerDNS/API/Handler.pm line 81

[Mon Sep 17 19:44:16 2012] [error] DBIx::Class::ResultSet::all(): DBI Exception: DBD::mysql::st execute failed: Unknown column 'me.ordername' in 'field list' at /home/powerdnsapi/PowerDNS-API/script/../lib/PowerDNS/API/Handler.pm line 81

**Comment by abh** [comment]
I think those are the PowerDNS 3.x schema updates that you need to put in.  PowerDNS 2.8 should work fine with the new schema (though you should test first).

**Comment by abh** [comment]
I'll be out for a few hours, but will reply to any updates when I come back.

**Comment by NuxRo** [comment]
Sure, take your time. I'll be off as well shortly.

Regarding the schema, I applied "less docs/schema.sql"; my powerdns version is 2.9.22.6 (can't upgrade to 3.x).
I'll be checking this page again tomorrow morning (gmt) if you have further advice.

**Comment by NuxRo** [comment]
Any other suggestions on how to proceed with this problem?

**Comment by abh** [comment]
You have to have the new columns from PowerDNS 3.x in the database, too. PowerDNS 2.9 is compatible with the new schema:

http://doc.powerdns.com/upgrades.html

**Comment by NuxRo** [comment]
Ahh, ok. Then something must be wrong in the DB. Thanks, I'll keep trying to get it to work.

**Comment by NuxRo** [comment]
Ask, thanks for your help. I started with a brand new DB on which I applied your full schema then imported the domains and records data separately. Now it seems to be working.
